"""Initial

Revision ID: f141560e6f05
Revises: 4f1f243bd6b2
Create Date: 2022-10-06 15:49:45.011730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f141560e6f05'
down_revision = '4f1f243bd6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
