"""Initial migration.

Revision ID: 775ff1d0fc3f
Revises: 7fcea1ab9db2
Create Date: 2022-10-09 22:58:16.367374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775ff1d0fc3f'
down_revision = '7fcea1ab9db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
